# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Economic_Machine_Code',
                'doc_host': 'https://gmaml.github.io',
                'git_url': 'https://github.com/gmaml/Economic_Machine_Code',
                'lib_path': 'Economic_Machine_Code'},
  'syms': {'Economic_Machine_Code.core': {'Economic_Machine_Code.core.foo': ('core.html#foo', 'Economic_Machine_Code/core.py')}}}
